name: Update README with GitHub Stats

on:
  schedule:
    - cron: "0 */5 * * *" # met à jour toutes les 12h
  workflow_dispatch: # permet de le lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.GH_STATS_TOKEN }}
